services:
  db:
    image: postgres:17
    container_name: hackathon-postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "hackathon-back"
    ports:
      - "5432:5432"
    networks:
      - shared
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:8.2.1
    container_name: hackathon-redis
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    networks:
      - shared
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "admin", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: hackathon-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - shared

  broker:
    image: apache/kafka:latest
    hostname: hackathon-broker
    container_name: hackathon-broker
    ports:
      - 9092:9092
    networks:
      - shared
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://hackathon-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@hackathon-broker:29093
      KAFKA_LISTENERS: PLAINTEXT://hackathon-broker:29092,CONTROLLER://hackathon-broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD", "bash", "-c", "nc -z localhost 9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: hackathon-kafka-ui
    ports:
      - "9020:8080"
    depends_on:
      - broker
    networks:
      - shared
    environment:
      AUTH_TYPE: "DISABLED"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: hackathon-broker:29092

  elasticsearch:
    image: elasticsearch:9.2.0
    container_name: hackathon-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - shared
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10

#  agent-cluster-apac:
#    build:
#      context: "./agent"
#      dockerfile: Dockerfile
#    environment:
#      APP_AGENT_ID: "6d40a8b9-a135-4b67-b96b-0579c6ae0f76"
#      APP_REGION: "APAC"
#      SUBSCRIBER_BROKERS: "hackathon-broker:29092"
#      SUBSCRIBER_GROUP_ID: "APAC"
#      SUBSCRIBER_TOPIC: "hosts-check-APAC"
#      SUBSCRIBER_BUFFER_SIZE: "1000"
#      PUBLISHER_BROKERS: "hackathon-broker:29092"
#      PUBLISHER_TOPIC: "hosts-checked"
#    depends_on:
#      broker:
#        condition: service_healthy
#    deploy:
#      replicas: 3
#    networks:
#      - shared
#    cap_add:
#      - NET_RAW
#      - NET_ADMIN
#
#  agent-cluster-eu:
#    build:
#      context: "./agent"
#      dockerfile: Dockerfile
#    environment:
#      APP_AGENT_ID: "1832f867-3295-4cb5-8b9d-f34fe8723560"
#      APP_REGION: "EU"
#      SUBSCRIBER_BROKERS: "hackathon-broker:29092"
#      SUBSCRIBER_GROUP_ID: "EU"
#      SUBSCRIBER_TOPIC: "hosts-check-EU"
#      SUBSCRIBER_BUFFER_SIZE: "1000"
#      PUBLISHER_BROKERS: "hackathon-broker:29092"
#      PUBLISHER_TOPIC: "hosts-checked"
#    depends_on:
#      broker:
#        condition: service_healthy
#    deploy:
#      replicas: 3
#    networks:
#      - shared
#    cap_add:
#      - NET_RAW
#      - NET_ADMIN
#
#  agent-cluster-us:
#    build:
#      context: "./agent"
#      dockerfile: Dockerfile
#    environment:
#      APP_AGENT_ID: "f022e955-1dff-4cf0-979a-80b118fa1126"
#      APP_REGION: "US"
#      SUBSCRIBER_BROKERS: "hackathon-broker:29092"
#      SUBSCRIBER_GROUP_ID: "US"
#      SUBSCRIBER_TOPIC: "hosts-check-US"
#      SUBSCRIBER_BUFFER_SIZE: "1000"
#      PUBLISHER_BROKERS: "hackathon-broker:29092"
#      PUBLISHER_TOPIC: "hosts-checked"
#    depends_on:
#      broker:
#        condition: service_healthy
#    deploy:
#      replicas: 3
#    networks:
#      - shared
#    cap_add:
#      - NET_RAW
#      - NET_ADMIN

  hackathon-back:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    container_name: hackathon-back
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.backend.docker.yml:/app/config/config.backend.docker.yml
    environment:
      CONFIG_PATH: "/app/config/config.backend.docker.yml"
    networks:
      - shared

  frontend:
    image: nginx:1.27-alpine
    container_name: hackathon-frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hackathon-back
    networks:
      - shared

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  shared:
    external: true
    name: my-shared-net
