app:
  agent_id: "6d40a8b9-a135-4b67-b96b-0579c6ae0f76"
  region: "GL"
subscriber:
  brokers:
    - "127.0.0.1:9092"
  group_id: "1"
  topic: "hosts-check-GL"
  buffer_size: 1000
publisher:
  brokers:
    - "127.0.0.1:9092"
  topic: "hosts-checked"
